<h2>Add Element To Cell Template</h2>
<?php
wcpt_elm_type_list(
  apply_filters(
    'wcpt_add_column_cell_element_array',
    array(
      'Title',
      'Product Image',
      'Price',
      'Rating',
      'Short Description',
      'Content',
      'Quantity',
      'Button',
      'Cart Button',
      'Download Button [pro]',
      'Link Button',
      'Remove [pro]',
      'Cart Quantity [pro]',
      'Favorite (addon) [pro]',
      'Custom Field',
      'Attribute',
      'Tags',
      'Taxonomy [pro]',
      'Multi Property Grid [pro]',
      'ToolTip [pro]',
      'Shortcode [pro]',
      'Select Variation [pro]',
      'Cart Form [pro]',
      'Checkbox [pro]',
      'Total [pro]',
      'Gallery [pro]',
      'On Sale [pro]',
      'Availability [pro]',
      'Position Number [pro]',
      'Dimensions [pro]',
      'Audio Player [pro]',
      // 'Video Player [pro]',
      'Author [pro]',
      'Height [pro]',
      'Width [pro]',
      'Length [pro]',
      'Weight [pro]',
      'Stock',
      'SKU',
      'GTIN',
      'Brand',
      'Product ID',
      'Category',
      'Product Link',
      'Date',
      'Line Separator',
      'Stick Separator [pro]',
      'Compare (3rd party) [pro]',
      'Quick view (3rd party) [pro]',
      'Text__Col',
      'HTML__Col',
      'Space__Col',
      'Dot__Col',
      'Icon__Col [pro]',
      'Media Image__Col [pro]',
    )
  )
);

do_action('wcpt_after_add_column_cell_element_buttons');
?>