<h2>Add ToolTip Element</h2>
<?php
wcpt_elm_type_list(array(
  // Essential properties
  'Title',
  'Product Image',
  'Price',
  'Rating',
  'Short Description',
  'Content',
  'Custom Field',
  'Attribute',
  'Brand',
  'Tags',
  'Cart Button',
  'Link Button',
  'Download Button',
  'Select Variation',
  'Multi Property Grid [pro]',
  'On Sale [pro]',
  'Availability [pro]',
  'Quantity',
  'Stock',
  'SKU',
  'Shortcode',
  'Category',
  'Product Link',
  'Date',
  'Line separator',
  'Text__Col',
  'HTML__Col',
  'Space__Col',
  'Dot__Col',
  'Icon__Col [pro]',
  'Media Image__Col [pro]',
  'Author [pro]',
  'Dimensions [pro]',
  'Height [pro]',
  'Width [pro]',
  'Length [pro]',
  'Weight [pro]',
));
?>